### ISSUE TITLE
ideas for creating an animation

### ISSUE THREAD

**Issue by raybellwaves** [benbovy/xvelmap#3]
This isn't an issue as such.
The package is great for showing the velocity dynamically at one time step.
I would like to create an animation.
I see you were able to create a .gif here https://github.com/benbovy/jupyterlab_velocity/blob/master/img/demo.gif
Mind sharing how you did that?
I could arduously create a .gif for each time-step then stitch them together.

My working directory is https://github.com/raybellwaves/SSElFaro/tree/master/winds

**Comment by raybellwaves** [comment]
I'll work this out. Probably not the package for temporal animations. Probably cleaner to use static images

**Comment by benbovy** [comment]
To create the GIF I actually used [this external tool](https://giphy.com/apps/giphycapture) to capture my screen :). But it's still shows one time step.

I agree that animations (i.e., smoothly updating the velocity field) would be nice, although I don't know if this is possible with the [leaflet-velocity](https://github.com/danwild/leaflet-velocity) library. What would be probably easier to do is using a slider (e.g., with jupyter widgets) for the time dimension that re-draws the map layer. Eventually some sort of integration of this package with [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet) would make sense.
