### ISSUE TITLE
jupyterlab_velocity doesn't support current version of jupyterlab

### ISSUE THREAD

**Issue by ericdill** [benbovy/xvelmap#6]
@raybellwaves just tried to launch this on binder but got an error. Figured you'd want to know:
```
ValueError: The extension "jupyterlab_velocity" does not yet support the current version of JupyterLab.
```

**Comment by raybellwaves** [comment]
Ah. This repo should probably be archived. and point development to ipyleaflet as in https://github.com/benbovy/xvelmap/issues/5
That issue should also be closed cc. @benbovy

**Comment by raybellwaves** [comment]
or more relevant point to https://github.com/davidbrochart/xarray_leaflet

**Comment by benbovy** [comment]
Yes good point @raybellwaves. I'm going to archive this repo and point to `xarray_leaflet`. I'll also archive `jupyterlab_velocity` and point to `ipyleaflet`.

**Comment by benbovy** [comment]
Actually velocity maps from xarray objects is still implemented in ipyleaflet (not yet in xarray_leaflet).
